learning_user/learning_user/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from userapp import views

urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    re_path('',include('userapp.urls')),
    re_path(r'^logout/$',views.user_logout,name='logout'),
    re_path(r'special/',views.special,name='special'),
    path('admin/', admin.site.urls),
]

learning_user/userapp/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'userapp'

urlpatterns = [
    re_path(r'^registration/',views.register,name='register'),
    re_path(r'^login/',views.user_login,name='login'),
]

learning_user/userapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)

    # addtional attributes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_user/userapp/forms.py
from django import forms
from django.contrib.auth.models import User
from userapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_user/userapp/views.py
from django.shortcuts import render
from userapp.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'userapp/index.html')

def register(request):
    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            registered = True
            profile.save()

        else:
            print(user_form.erros,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'userapp/registration.html', {
        'user_form':user_form,
        'profile_form':profile_form,
        'registered':registered,
    })

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT IS NOT ACTIVE")

        else:
            print("SOMEONE TRIED TO LOGIN AND FAILED")
            print(f"Username: {username} and password: {password}")
            return HttpResponse("invalid login details supplied")

    else:
        return render(request,'userapp/login.html', {})

@login_required # login required to log out
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def special(request):
    return HttpResponse("You are logged in, Nice")

learning_user/templates/userapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welcome to HOMPAGE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
      integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a  class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a  class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a  class="navbar-link" href="{% url 'userapp:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout'%}">Log out</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'userapp:login' %}">Log in</a></li>
          {% endif %}
        </ul>
      </div>

      {% block body_block %}
      {% endblock %}

    </nav>

  </body>
</html>

learning_user/templates/userapp/index.html
{% extends 'userapp/base.html' %}
  {% block body_block %}
    <div class="jumbotron">
      <h1>Welcome to DJANGO L5</h1>
    </div>
  {% endblock %}

learning_user/templates/userapp/login.html
{% extends 'userapp/base.html' %}
  {% block body_block %}

    <div class="jumbotron">
      <form action="{% url 'userapp:login' %}" method="post">
        <h1>Please login</h1>
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" value="" placeholder="Username">
        <label for="password">Password</label>
        <input type="password" name="password" value="">
        <input type="submit" name="" value="Login">
      </form>
    </div>

  {% endblock %}

learning_user/templates/userapp/registration.html
{% extends 'userapp/base.html' %}
{% load staticfiles %}


  {% block body_block %}
    <div class="jumnbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form</h3>

        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        {% endif %}
    </div>
  {% endblock %}